from src.llm.llm_client import create_client
def generate_business_report(prompt: str) -> str:
    """
    Sends a prompt to Gemini and returns the generated response.

    Parameters
    ----------
    prompt : str
        The prompt generated by one of the functions in prompts.py

    Returns
    -------
    str
        Gemini's generated business report.
    """

    client = create_client()

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    return response.text