from pathlib import Path
def save_report(report: str, filename: str):
    """
    Save the generated report as a Markdown file.

    Parameters
    ----------
    report : str
        The report generated by Gemini.

    filename : str
        Name of the output Markdown file.
    """

    output_dir = Path("outputs")
    output_dir.mkdir(exist_ok=True)

    output_path = output_dir / filename

    with open(output_path, "w", encoding="utf-8") as file:
        file.write(report)

    print(f"\nReport saved successfully to: {output_path}")